name: CI

on:
  push:
    branches: ['*']

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [angular-portfolio, react-portfolio]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      # Lint both apps
      - run: pnpm exec nx run ${{ matrix.app }}:lint

      # Build both apps
      - run: pnpm exec nx run ${{ matrix.app }}:build

      # Test both apps
      - run: pnpm exec nx run ${{ matrix.app }}:test --code-coverage
