name: CI Checks

on:
  push:
    branches:
      - master
      - angular-portfolio
      - react-portfolio
  pull_request:
    branches:
      - master
      - angular-portfolio
      - react-portfolio

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [angular-portfolio, react-portfolio]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: Install dependencies
        run: npm ci

      - name: Install Nx globally
        run: npm install -g nx

      - name: Reset Nx cache
        run: npx nx reset

      - name: Lint ${{ matrix.app }}
        run: npx nx lint ${{ matrix.app }} --verbose

      - name: Build ${{ matrix.app }}
        run: npx nx build ${{ matrix.app }}

      - name: Test ${{ matrix.app }} with coverage
        run: npx nx test ${{ matrix.app }} --code-coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.app }}
          path: coverage/${{ matrix.app }}
