name: CI

on:
  push:
    branches:
      - master
      - angular-portfolio
      - react-portfolio
  pull_request:
    branches:
      - master
      - angular-portfolio
      - react-portfolio

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [angular-portfolio, react-portfolio]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: npm cache verify

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Install dependencies using npm
      - run: |
          npm install nx@20.3.1
          npm install @nrwl/react@18.3.1
          npm install @nrwl/web@19.8.4
          npm ci

      - run: npm exec nx reset
      - run: npm exec nx cache clear

      - uses: nrwl/nx-set-shas@v4

      # Lint both apps
      - run: npm exec nx run ${{ matrix.app }}:lint

      # Build both apps
      - run: npm exec nx run ${{ matrix.app }}:build

      # Test both apps
      - run: npm exec nx run ${{ matrix.app }}:test --code-coverage
