name: CI

on:
  push:
    branches:
      - master
      - angular-portfolio
      - react-portfolio
  pull_request:
    branches:
      - master
      - angular-portfolio
      - react-portfolio

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

  prettier:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Prettier formatting
        run: npx prettier --check .

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ESLint
        run: npx eslint "apps/**/*.{js,ts,tsx}" "libs/**/*.{js,ts,tsx}"

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Jest tests
        run: npx jest --coverage

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Angular app
        run: npm run build:angular # customize this command

      - name: Build React app
        run: npm run build:react # customize this too
