name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
  pull_request:

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: |
          npm install nx@20.3.1
          npm install @nrwl/react@18.3.1
          npm install @nrwl/web@19.8.4
          HUSKY_SKIP_INSTALL=1
          npm ci

      - uses: nrwl/nx-set-shas@v4

      - run: npm exec nx reset

      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t lint test build
